# Generated by Django 5.2.8 on 2026-01-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='case_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
