# Generated by Django 5.2.8 on 2026-01-28 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0002_consultationrequest_case_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='attorney.consultationrequest'),
        ),
    ]
