# Generated by Django 5.2.8 on 2026-01-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(default='pending', max_length=32),
        ),
    ]
