# Generated by Django 5.2.8 on 2026-02-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0007_attorneyrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorneyrating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
