# Generated by Django 5.2.8 on 2025-12-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_appleusertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_of_law',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_legal_area',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('attorney', 'Attorney'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
