# Generated by Django 5.2.8 on 2026-01-27 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_appleusertoken_user_alter_token_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('area_of_law', models.CharField(blank=True, max_length=255)),
                ('bar_license_number', models.CharField(blank=True, max_length=128)),
                ('bio', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, help_text='Comma-separated list of languages', max_length=255)),
                ('experience', models.CharField(blank=True, help_text="Short summary like '8+ years'", max_length=255)),
                ('response_time', models.CharField(blank=True, help_text="E.g. 'Responds in ~2 hrs'", max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attorney_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
