# Generated by Django 5.2.8 on 2026-01-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_attorney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='area_of_law',
        ),
        migrations.RemoveField(
            model_name='user',
            name='designation',
        ),
    ]
