# Generated by Django 5.2.8 on 2026-02-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_area_of_law_remove_user_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_legal_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
