# Generated by Django 5.2.8 on 2026-03-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_location_alter_user_preferred_legal_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', help_text='Attorney subscription tier', max_length=20),
        ),
    ]
