# Generated by Django 5.2.8 on 2026-03-25 22:46
# This migration is empty - the field alteration was moved to migration 0009

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_set_tier_null_for_existing'),
    ]

    operations = [
        # AlterField operation moved to 0009_set_tier_null_for_existing
    ]
